name: bdlogging
description: A Flutter package that provide logging capability for flutter apps.
version: 1.4.1
homepage: https://github.com/bitsydarel/bdlogging

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  async: '>=2.13.0 <3.0.0'
  collection: '>=1.19.1 <2.0.0'
  cryptography: '>=2.7.0 <3.0.0'
  http: '>=1.2.1 <2.0.0'
  intl: '>=0.20.0 <1.0.0'
  io: '>=1.0.5 <2.0.0'
  meta: '>=1.16.0 <2.0.0'
  path: '>=1.9.1 <2.0.0'

dev_dependencies:
  flutter_code_style: ^2.2.0
  mocktail: '>=1.0.4 <2.0.0'
  test: '>=1.25.9 <2.0.0'
