name: bdlogging_firebase
description: A Flutter package that provide BDLogHandler for firebase services.
version: 1.3.2
homepage: https://github.com/bitsydarel/bdlogging

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  bdlogging: ^1.3.2
  firebase_crashlytics: '>=5.0.0 <6.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_code_style: ^2.2.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec